name: Run Playwright Tests in Docker

# Controls when the workflow will run.
on:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
env:
  ENV: ${{ vars.ENV }}
  UI_USERNAME: ${{ secrets.UI_USERNAME }}
  UI_PASSWORD: ${{ secrets.UI_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code.
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build the Docker image.
      - name: Build Docker Image
        # The -t option allows naming the image. You can use any name you prefer, 
        # such as 'playwright-tests', 'my-playwright-image', or 'ci-playwright-image'.
        # Ensure consistency when referencing the image later in the workflow.
        run: docker build -t playwright-tests .

      # Step 3: Run the Docker container and execute the tests.
      - name: Run Playwright Tests
        # The image name used here must match the one specified during the build step.
        run: |
          docker run --rm \
            -e ENV=${{ vars.ENV }} \
            -e UI_USERNAME=${{ secrets.UI_USERNAME }} \
            -e UI_PASSWORD=${{ secrets.UI_PASSWORD }} \
            playwright-tests
